# Generated by Django 5.0.1 on 2024-01-30 04:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_doctor_id_number_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
